# API

比如在[yelp网站](https://www.yelp.com/developers/documentation/v3/get_started)就有搜索api：GET https://api.yelp.com/v3/businesses/search

Client ID

EEk1utGIe31Om919mFHhYQ

API Key

n0KAipvvIT2RFIRot9Ge20ZMUNOh18llpWTWq5rzxPtBB63OXKad0Mk-SF_ooYn4GIu0ekHlDikIUyjxOPIgtsvpoMWf5E03zQKuk-_Y0c6rhYAKzBxAPBBDnshjYnYx

In [13]:
import requests

url = "http://api.yelp.com/v3/businesses/search"
api_key = "n0KAipvvIT2RFIRot9Ge20ZMUNOh18llpWTWq5rzxPtBB63OXKad0Mk-SF_ooYn4GIu0ekHlDikIUyjxOPIgtsvpoMWf5E03zQKuk-_Y0c6rhYAKzBxAPBBDnshjYnYx"
headers = {
    "Authorization": "Bearer " + api_key
}
params = {
    "term": "Barber",
    "location": "NYC"
}
response = requests.get(url, headers=headers, params=params)

businesses = result = response.json()["businesses"]
names = [bussiness["name"] for bussiness in businesses if bussiness["rating"] > 4.5 ]
print(names)

['Next Level Barber Shop', "Barber's Point", '12 Pell', 'The Flying Row', 'Hairrari East Village']


## 隐藏api

创建一个新的py文件叫config.py，然后将api放入，然后在.gitignore文件中添加该文件名

## 发送信息 20min左右

twilio

## Web Scraping 网页抓取/爬虫 25min

In [27]:
import requests
from bs4 import BeautifulSoup
url = "https://yjszs.ecnu.edu.cn/system/ssfsmd_list.asp?yxid=160"
response = requests.get(url,verify=False)
print(response)
# response = requests.get("https://stackoverflow.com/questions")
response.encoding = "gb2312"
soup = BeautifulSoup(response.text, "html.parser")

questions = soup.select("#Presentation")
print(questions)
print(type(questions[0]))

C:\Users\JackyLee\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'yjszs.ecnu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


<Response [200]>
[<table id="Presentation">
<caption>华东师范大学软件工程学院2022年硕士研究生招生复试名单（动态更新）</caption>
<tr>
<th>序号</th>
<th>招生年份</th>
<th>学科</th>
<th>研究方向</th>
<th>学习形式</th>
<th>考生编号</th>
<th>姓名</th>
<th>第一单元</th>
<th>第二单元</th>
<th>第三单元</th>
<th>第四单元</th>
<th>政策加分</th>
<th>初试总分</th>
<th>专项计划</th>
<th>志愿情况</th>
<th>备注</th>
</tr>
<tr bgcolor="#FFFFFF">
<tr>
<td>1</td>
<td>2022</td>
<td style="text-align:left">083500软件工程</td>
<td style="text-align:left">01软件科学与技术</td>
<td>

        
        1全日制

        

       </td>
<td>102692160037267</td>
<td>吴惠玲</td>
<td> 67</td>
<td>77</td>
<td>128</td>
<td>123</td>
<td></td>
<td>395</td>
<td></td>
<td> 一志愿</td>
<td> </td>
</tr>
<tr>
<td>2</td>
<td>2022</td>
<td style="text-align:left">083500软件工程</td>
<td style="text-align:left">01软件科学与技术</td>
<td>

        
        1全日制

        

       </td>
<td>102692160037328</td>
<td>杨方圆</td>
<td> 61</td>
<td>67</td>
<td>137</td>
<td>129</td>
<td></td>
<td>394</td>
<td></td>
<td> 一志愿</td>
<td> </td>
</tr>
<tr>
<td

## selenium 35min

## pdf 45min

pypdf2

## excel 52min

openpyxl

### Command query separation

## Numpy `1:06:38`

In [45]:
import numpy as np

array = np.array([1,2,3])
print(array)
print(type(array))

array = np.array([ [1,2,3], [4,5,6]])
print(array.shape) # 返回长度

np.zeros((3,4),dtype=int) # 返回一个3*4大小的全零(浮点型）矩阵
np.zeros((3,4),dtype=int) # 返回一个3*4大小的全零（整形）矩阵
np.ones((3,4))
np.full((3,4),5)
array = np.random.random((3,4))
print(array)
print(array[0,0])  # 返回第一行第一列，或者写作array[0][0]
print(array > 0.2) # 返回布尔矩阵
print(array[array > 0.2])
print(np.sum(array))
print(np.floor(array))  # 或者ceil， round

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
[[0.91396874 0.45438782 0.49141015 0.19692831]
 [0.14826035 0.68878725 0.5299639  0.85806677]
 [0.43692462 0.23249689 0.54762984 0.04964045]]
0.9139687446245099
[[ True  True  True False]
 [False  True  True  True]
 [ True  True  True False]]
[0.91396874 0.45438782 0.49141015 0.68878725 0.5299639  0.85806677
 0.43692462 0.23249689 0.54762984]
5.548465098432171
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
import numpy as np

first = np.array([1,2,3])
second = np.array([1,2,3])

print(first+2)

[3 4 5]
